#############################################################################
# Makefile for building: GPSUtility
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Sep 30 00:42:38 2010
# Project:  GPSUtility.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile GPSUtility.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		locationwidget.cpp \
		mapdialog.cpp \
		nmeaparser.cpp \
		nmeasatellitelist.cpp \
		qseriallinereader.cpp \
		connectiondialog.cpp \
		signalmeter.cpp \
		locationserverdialog.cpp \
		gpsutilityapplication.cpp moc_mainwindow.cpp \
		moc_locationwidget.cpp \
		moc_mapdialog.cpp \
		moc_qseriallinereader.cpp \
		moc_connectiondialog.cpp \
		moc_signalmeter.cpp \
		moc_locationserverdialog.cpp \
		moc_gpsutilityapplication.cpp \
		qrc_http.cpp
OBJECTS       = main.o \
		mainwindow.o \
		locationwidget.o \
		mapdialog.o \
		nmeaparser.o \
		nmeasatellitelist.o \
		qseriallinereader.o \
		connectiondialog.o \
		signalmeter.o \
		locationserverdialog.o \
		gpsutilityapplication.o \
		moc_mainwindow.o \
		moc_locationwidget.o \
		moc_mapdialog.o \
		moc_qseriallinereader.o \
		moc_connectiondialog.o \
		moc_signalmeter.o \
		moc_locationserverdialog.o \
		moc_gpsutilityapplication.o \
		qrc_http.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		GPSUtility.pro
QMAKE_TARGET  = GPSUtility
DESTDIR       = 
TARGET        = GPSUtility

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_locationwidget.h ui_mapdialog.h ui_connectiondialog.h ui_signalmeter.h ui_locationserverdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPSUtility.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile GPSUtility.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile GPSUtility.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GPSUtility1.0.0 || $(MKDIR) .tmp/GPSUtility1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GPSUtility1.0.0/ && $(COPY_FILE) --parents mainwindow.h locationwidget.h mapdialog.h nmeaparser.h nmeasatellitelist.h qseriallinereader.h connectiondialog.h signalmeter.h locationserverdialog.h gpsutilityapplication.h .tmp/GPSUtility1.0.0/ && $(COPY_FILE) --parents http.qrc .tmp/GPSUtility1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp locationwidget.cpp mapdialog.cpp nmeaparser.cpp nmeasatellitelist.cpp qseriallinereader.cpp connectiondialog.cpp signalmeter.cpp locationserverdialog.cpp gpsutilityapplication.cpp .tmp/GPSUtility1.0.0/ && $(COPY_FILE) --parents mainwindow.ui locationwidget.ui mapdialog.ui connectiondialog.ui signalmeter.ui locationserverdialog.ui .tmp/GPSUtility1.0.0/ && (cd `dirname .tmp/GPSUtility1.0.0` && $(TAR) GPSUtility1.0.0.tar GPSUtility1.0.0 && $(COMPRESS) GPSUtility1.0.0.tar) && $(MOVE) `dirname .tmp/GPSUtility1.0.0`/GPSUtility1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GPSUtility1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_locationwidget.cpp moc_mapdialog.cpp moc_qseriallinereader.cpp moc_connectiondialog.cpp moc_signalmeter.cpp moc_locationserverdialog.cpp moc_gpsutilityapplication.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_locationwidget.cpp moc_mapdialog.cpp moc_qseriallinereader.cpp moc_connectiondialog.cpp moc_signalmeter.cpp moc_locationserverdialog.cpp moc_gpsutilityapplication.cpp
moc_mainwindow.cpp: locationwidget.h \
		signalmeter.h \
		mapdialog.h \
		qseriallinereader.h \
		nmeaparser.h \
		nmeasatellitelist.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_locationwidget.cpp: locationwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) locationwidget.h -o moc_locationwidget.cpp

moc_mapdialog.cpp: mapdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mapdialog.h -o moc_mapdialog.cpp

moc_qseriallinereader.cpp: qseriallinereader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qseriallinereader.h -o moc_qseriallinereader.cpp

moc_connectiondialog.cpp: connectiondialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) connectiondialog.h -o moc_connectiondialog.cpp

moc_signalmeter.cpp: signalmeter.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) signalmeter.h -o moc_signalmeter.cpp

moc_locationserverdialog.cpp: locationserverdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) locationserverdialog.h -o moc_locationserverdialog.cpp

moc_gpsutilityapplication.cpp: qseriallinereader.h \
		mainwindow.h \
		locationwidget.h \
		signalmeter.h \
		mapdialog.h \
		nmeaparser.h \
		nmeasatellitelist.h \
		gpsutilityapplication.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gpsutilityapplication.h -o moc_gpsutilityapplication.cpp

compiler_rcc_make_all: qrc_http.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_http.cpp
qrc_http.cpp: http.qrc \
		resources/html/gmapjs.html \
		resources/images/bullet_green.png
	/usr/bin/rcc -name http http.qrc -o qrc_http.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_locationwidget.h ui_mapdialog.h ui_connectiondialog.h ui_signalmeter.h ui_locationserverdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_locationwidget.h ui_mapdialog.h ui_connectiondialog.h ui_signalmeter.h ui_locationserverdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_locationwidget.h: locationwidget.ui
	/usr/bin/uic-qt4 locationwidget.ui -o ui_locationwidget.h

ui_mapdialog.h: mapdialog.ui
	/usr/bin/uic-qt4 mapdialog.ui -o ui_mapdialog.h

ui_connectiondialog.h: connectiondialog.ui
	/usr/bin/uic-qt4 connectiondialog.ui -o ui_connectiondialog.h

ui_signalmeter.h: signalmeter.ui
	/usr/bin/uic-qt4 signalmeter.ui -o ui_signalmeter.h

ui_locationserverdialog.h: locationserverdialog.ui
	/usr/bin/uic-qt4 locationserverdialog.ui -o ui_locationserverdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		locationwidget.h \
		signalmeter.h \
		mapdialog.h \
		qseriallinereader.h \
		nmeaparser.h \
		nmeasatellitelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp connectiondialog.h \
		locationserverdialog.h \
		mainwindow.h \
		locationwidget.h \
		signalmeter.h \
		mapdialog.h \
		qseriallinereader.h \
		nmeaparser.h \
		nmeasatellitelist.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

locationwidget.o: locationwidget.cpp locationwidget.h \
		ui_locationwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o locationwidget.o locationwidget.cpp

mapdialog.o: mapdialog.cpp mapdialog.h \
		ui_mapdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapdialog.o mapdialog.cpp

nmeaparser.o: nmeaparser.cpp nmeaparser.h \
		nmeasatellitelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nmeaparser.o nmeaparser.cpp

nmeasatellitelist.o: nmeasatellitelist.cpp nmeasatellitelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nmeasatellitelist.o nmeasatellitelist.cpp

qseriallinereader.o: qseriallinereader.cpp qseriallinereader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qseriallinereader.o qseriallinereader.cpp

connectiondialog.o: connectiondialog.cpp connectiondialog.h \
		ui_connectiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectiondialog.o connectiondialog.cpp

signalmeter.o: signalmeter.cpp signalmeter.h \
		ui_signalmeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalmeter.o signalmeter.cpp

locationserverdialog.o: locationserverdialog.cpp locationserverdialog.h \
		ui_locationserverdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o locationserverdialog.o locationserverdialog.cpp

gpsutilityapplication.o: gpsutilityapplication.cpp gpsutilityapplication.h \
		qseriallinereader.h \
		mainwindow.h \
		locationwidget.h \
		signalmeter.h \
		mapdialog.h \
		nmeaparser.h \
		nmeasatellitelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpsutilityapplication.o gpsutilityapplication.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_locationwidget.o: moc_locationwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_locationwidget.o moc_locationwidget.cpp

moc_mapdialog.o: moc_mapdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapdialog.o moc_mapdialog.cpp

moc_qseriallinereader.o: moc_qseriallinereader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qseriallinereader.o moc_qseriallinereader.cpp

moc_connectiondialog.o: moc_connectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectiondialog.o moc_connectiondialog.cpp

moc_signalmeter.o: moc_signalmeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalmeter.o moc_signalmeter.cpp

moc_locationserverdialog.o: moc_locationserverdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_locationserverdialog.o moc_locationserverdialog.cpp

moc_gpsutilityapplication.o: moc_gpsutilityapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gpsutilityapplication.o moc_gpsutilityapplication.cpp

qrc_http.o: qrc_http.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_http.o qrc_http.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

